export type CityGuide = {
  highlightsDe: string[];
  highlightsEn: string[];
  stayTipDe: string;
  stayTipEn: string;
  savingTipDe: string;
  savingTipEn: string;
  travelNoteDe: string;
  travelNoteEn: string;
  premiumIntroDe?: string;
  premiumIntroEn?: string;
  mustSeeDe?: string[];
  mustSeeEn?: string[];
  stayAreasDe?: string[];
  stayAreasEn?: string[];
  timingDe?: string;
  timingEn?: string;
};

export const cityGuides: Record<string, CityGuide> = {
  amsterdam: {
    highlightsDe: ["Grachtengürtel", "Jordaan", "Museumsviertel"],
    highlightsEn: ["Canal Belt", "Jordaan", "Museum Quarter"],
    stayTipDe: "Wenn du Amsterdam entspannt erleben willst, sind Jordaan, De Pijp oder die Gegend rund um das Museumsviertel oft spannender als nur direkt am Hauptbahnhof.",
    stayTipEn: "If you want a calmer Amsterdam stay, Jordaan, De Pijp and the Museum Quarter are often more rewarding than staying right by the central station.",
    savingTipDe: "Amsterdam wird an Wochenenden, Feiertagen und zu Event-Zeiten schnell teuer. Wer früh flexibel bucht, hat oft später noch gute Chancen auf bessere Raten.",
    savingTipEn: "Amsterdam gets expensive quickly on weekends, holidays and event dates. If you book early with flexibility, you often still have a chance to catch a better rate later.",
    travelNoteDe: "Für einen klassischen Citytrip lohnen sich Bootsfahrten, Museen und Spaziergänge durch die kleineren Viertel mehr als nur die typischen Hotspots.",
    travelNoteEn: "For a classic city trip, canal cruises, museums and wandering through smaller neighborhoods tend to be more rewarding than only ticking off the biggest hotspots.",
    premiumIntroDe: "Amsterdam funktioniert am besten, wenn du Wasser, Viertel und Tempo mitdenkst. Die Stadt wirkt nicht über große Sehenswürdigkeiten, sondern über kleine Straßenzüge, Cafes und den Wechsel zwischen lebendig und ruhig.",
    premiumIntroEn: "Amsterdam works best when you think in terms of water, neighborhoods and rhythm. The city shines less through giant landmarks and more through smaller streets, cafes and the balance between lively and calm.",
    mustSeeDe: ["Frühe Grachtenrunde", "Jordaan am Abend", "Museumsplein ohne Mittagsstress"],
    mustSeeEn: ["Early canal walk", "Jordaan in the evening", "Museumsplein outside midday rush"],
    stayAreasDe: ["Jordaan für Atmosphäre", "De Pijp für Cafes", "Museumsviertel für kurze Wege"],
    stayAreasEn: ["Jordaan for atmosphere", "De Pijp for cafes", "Museum Quarter for walkability"],
    timingDe: "Besonders stark schwanken Preise rund um Fr-So, Feiertage und Eventwochen. Unter der Woche wirkt Amsterdam oft ruhiger und preislich interessanter.",
    timingEn: "Prices move most around Fri-Sun, holidays and event weeks. Midweek Amsterdam is often calmer and more attractive on price.",
  },
  paris: {
    highlightsDe: ["Marais", "Saint-Germain-des-Pres", "Montmartre"],
    highlightsEn: ["Le Marais", "Saint-Germain-des-Pres", "Montmartre"],
    stayTipDe: "Wenn du viel zu Fuß machen willst, sind zentrale Viertel wie Marais oder Saint-Germain oft praktischer als sehr günstige Randlagen.",
    stayTipEn: "If you want to do a lot on foot, central areas like Le Marais or Saint-Germain are often more practical than very cheap outer districts.",
    savingTipDe: "Paris reagiert stark auf Messen, Feiertage und lange Wochenenden. Gerade bei Frühbuchungen lohnt sich Preisüberwachung bis kurz vor Anreise.",
    savingTipEn: "Paris reacts strongly to fairs, holidays and long weekends. Especially with early bookings, price tracking can pay off right up to arrival.",
    travelNoteDe: "Kleine Cafe-Pausen, Spaziergänge an der Seine und ein klarer Plan pro Arrondissement machen den Aufenthalt meist besser als zu viele Programmpunkte.",
    travelNoteEn: "Small cafe breaks, Seine walks and a simple plan per arrondissement often make the trip better than cramming in too many attractions.",
    premiumIntroDe: "Paris wird schnell überladen geplant. Viel schöner wird die Stadt, wenn du einzelne Arrondissements bewusst erlebst: morgens ein Museum, nachmittags ein Viertel, abends gutes Essen statt zehn Haken auf einer Liste.",
    premiumIntroEn: "Paris is often overplanned. It becomes much better when you experience one arrondissement at a time: a museum in the morning, a neighborhood in the afternoon and a strong dinner instead of ten boxes ticked.",
    mustSeeDe: ["Seine-Spaziergang bei Sonnenuntergang", "Marais mit kleinen Boutiquen", "Montmartre früh statt mittags"],
    mustSeeEn: ["Seine walk at sunset", "Le Marais and its smaller boutiques", "Montmartre early instead of midday"],
    stayAreasDe: ["Saint-Germain für klassische Paris-Stimmung", "Marais für kurze Wege", "Canal Saint-Martin für etwas entspanntere Energie"],
    stayAreasEn: ["Saint-Germain for classic Paris atmosphere", "Le Marais for walkability", "Canal Saint-Martin for a slightly calmer vibe"],
    timingDe: "Preisbewegungen sind oft stark rund um Fashion Week, Messen, Brückentage und lange Wochenenden. Gerade dann lohnt sich Monitoring bis kurz vor Anreise.",
    timingEn: "Price movement is often strong around fashion weeks, fairs, bridge holidays and long weekends. Those are exactly the moments when tracking pays off.",
  },
  barcelona: {
    highlightsDe: ["El Born", "Eixample", "Barceloneta"],
    highlightsEn: ["El Born", "Eixample", "Barceloneta"],
    stayTipDe: "Eixample ist oft ein guter Mix aus Lage, Restaurants und Ruhe. Direkt an den touristischsten Hotspots ist es oft lauter und teurer.",
    stayTipEn: "Eixample often gives you a great balance of location, food and calm. Right next to the busiest hotspots it is usually louder and pricier.",
    savingTipDe: "Barcelona kann rund um Wochenenden, Messen und Sommertermine stark schwanken. Flexible Raten sind hier besonders wertvoll.",
    savingTipEn: "Barcelona can swing hard around weekends, fairs and summer dates. Flexible rates are especially valuable here.",
    travelNoteDe: "Für viele ist die beste Mischung: Altstadt, Tapas, Strand und ein klar gesetzter Architektur-Tag statt alles auf einmal.",
    travelNoteEn: "For many travellers, the best mix is old town, tapas, beach time and one dedicated architecture day instead of trying to do everything at once.",
    premiumIntroDe: "Barcelona lebt von Kontrasten: Meer, Altstadt, breite Boulevards und starke Architektur. Gute Stadtseiten sollten genau das spiegeln, statt nur eine billige Hotel-Liste aneinanderzureihen.",
    premiumIntroEn: "Barcelona lives on contrast: sea, old town, wide boulevards and striking architecture. Strong city pages should reflect that instead of just stacking generic hotel blurbs.",
    mustSeeDe: ["Passeig de Gracia am frühen Morgen", "Tapas-Abend in El Born", "Sonnenuntergang am Bunkers del Carmel"],
    mustSeeEn: ["Passeig de Gracia early in the morning", "Tapas evening in El Born", "Sunset at Bunkers del Carmel"],
    stayAreasDe: ["Eixample für Balance", "El Born für Atmosphäre", "Poblenou für etwas mehr Ruhe nah am Wasser"],
    stayAreasEn: ["Eixample for balance", "El Born for atmosphere", "Poblenou for a calmer stay near the water"],
    timingDe: "Rund um Messen, Wochenenden und Hochsommer verschiebt sich die Preisstruktur stark. Wer früh bucht, sollte Barcelona fast immer weiter beobachten.",
    timingEn: "Around fairs, weekends and high summer the price structure moves hard. If you booked early, Barcelona is almost always worth monitoring.",
  },
  london: {
    highlightsDe: ["Covent Garden", "South Bank", "Notting Hill"],
    highlightsEn: ["Covent Garden", "South Bank", "Notting Hill"],
    stayTipDe: "In London lohnt es sich oft, eher nach guter Tube-Anbindung als nach absoluter Innenstadtlage zu buchen.",
    stayTipEn: "In London it often makes more sense to book around strong Tube access than chasing the most central postcode.",
    savingTipDe: "London-Hotels reagieren stark auf Konzerte, Fußball, Konferenzen und Ferienzeiten. Früh buchen und dann weiter tracken ist hier besonders sinnvoll.",
    savingTipEn: "London hotels react strongly to concerts, football, conferences and holiday periods. Booking early and then keeping track is especially useful here.",
    travelNoteDe: "South Bank, Parks, Pubs und ein gutes Viertel zum Zurückkommen machen London oft angenehmer als nur Sehenswürdigkeiten abzuhaken.",
    travelNoteEn: "South Bank walks, parks, pubs and having one good home neighborhood often make London better than just ticking off landmarks.",
    premiumIntroDe: "London ist selten die Stadt für den billigsten Zufallstreffer. Entscheidend sind Verbindung, Viertelgefühl und eventbedingte Sprünge. Genau deshalb ist London eine der besten Städte für späteres Rebooking.",
    premiumIntroEn: "London is rarely about finding the cheapest random room. Connection, neighborhood feel and event-driven spikes matter far more. That is exactly why London is one of the best cities for later rebooking.",
    mustSeeDe: ["South Bank zu Fuß", "Abend im Pub-Viertel", "Ein halber Tag nur für Parks und Museen"],
    mustSeeEn: ["South Bank on foot", "An evening in a pub neighborhood", "Half a day just for parks and museums"],
    stayAreasDe: ["Bloomsbury für Museen", "South Bank für Energie", "Paddington nur bei guter Verbindung und fairem Preis"],
    stayAreasEn: ["Bloomsbury for museums", "South Bank for energy", "Paddington only if the connection and price are right"],
    timingDe: "Bei Konzerten, Fußball, Schulferien und großen Konferenzen springt London extrem. Preisalarme sind hier oft kein Nice-to-have, sondern echter Schutz vor Überzahlung.",
    timingEn: "Concerts, football, school holidays and large conferences move London dramatically. Alerts here are often not a nice extra but real protection against overpaying.",
  },
  rom: {
    highlightsDe: ["Trastevere", "Centro Storico", "Monti"],
    highlightsEn: ["Trastevere", "Centro Storico", "Monti"],
    stayTipDe: "Wenn du Rom atmosphärisch erleben willst, sind Trastevere oder Monti oft spannender als sehr anonyme Kettenlagen außerhalb.",
    stayTipEn: "If you want the atmosphere of Rome, areas like Trastevere or Monti are often more rewarding than anonymous chain-hotel zones farther out.",
    savingTipDe: "Rom ist rund um Feiertage, Frühling und Herbst stark gefragt. Gerade bei länger im Voraus gebuchten Aufenthalten lohnt sich Monitoring.",
    savingTipEn: "Rome sees strong demand around holidays, spring and autumn. Monitoring is especially useful if you booked well in advance.",
    travelNoteDe: "Die Stadt funktioniert oft am besten mit viel Laufen, langen Abendessen und einem lockeren Plan pro Stadtteil.",
    travelNoteEn: "Rome often works best with lots of walking, long dinners and a relaxed plan focused on one neighborhood at a time.",
    premiumIntroDe: "Rom wirkt über Atmosphäre, Wege und Tageszeiten. Die schönsten Stunden sind oft die frühen und späten, und genau dann spürt man auch, welche Lage sich wirklich lohnt.",
    premiumIntroEn: "Rome works through atmosphere, walking and the rhythm of the day. The best hours are often early and late, and that is exactly when you feel whether your location was worth it.",
    mustSeeDe: ["Trastevere nach Sonnenuntergang", "Morgens rund ums Forum", "Ein ruhiger Aperitivo statt noch ein Museum"],
    mustSeeEn: ["Trastevere after sunset", "Morning around the Forum", "A quiet aperitivo instead of one more museum"],
    stayAreasDe: ["Monti für Stil und Nähe", "Centro Storico für klassische Wege", "Prati für etwas mehr Ruhe"],
    stayAreasEn: ["Monti for style and proximity", "Centro Storico for classic walkability", "Prati for a calmer feel"],
    timingDe: "Frühling, Herbst und Feiertage ziehen Preise in Rom schnell an. Gerade bei früher Buchung lohnt sich tägliches Nachverfolgen bis nah an die Anreise.",
    timingEn: "Spring, autumn and holidays push Rome up fast. If you booked early, daily tracking often pays right up until close to arrival.",
  },
  wien: {
    highlightsDe: ["Innere Stadt", "MuseumsQuartier", "Neubau"],
    highlightsEn: ["Innere Stadt", "MuseumsQuartier", "Neubau"],
    stayTipDe: "Wenn du Kultur, Cafes und gute Wege kombinieren willst, sind Neubau oder die Gegend um das MuseumsQuartier oft stark. Die Innere Stadt ist prestigereich, aber auch teuer — Neubau gibt dir fast dieselben Wege zu deutlich entspannteren Preisen.",
    stayTipEn: "If you want culture, cafes and easy walking distances, Neubau and the area around the MuseumsQuartier are often strong choices. The Innere Stadt is prestigious but expensive — Neubau gives you almost the same access at noticeably calmer prices.",
    savingTipDe: "Wien wirkt oft stabil, aber Messen, Adventszeit, Opernball-Wochenende und Konzerttermine bewegen die Preise stark. Wer diese Spitzen kennt, kann sie entweder meiden oder bei früherer Buchung gezielt Preisalarme setzen.",
    savingTipEn: "Vienna can look stable, but fairs, Christmas season, the Opera Ball weekend and concert dates push prices hard. Knowing these spikes lets you either avoid them or set targeted price alerts after an early booking.",
    travelNoteDe: "Schloss Schönbrunn früh morgens ohne Massen, ein echtes Kaffeehaus für das Frühstück, abends ein Konzert oder eine Oper — das ist Wien in seiner besten Form. Nicht versuchen, alles auf einmal zu sehen.",
    travelNoteEn: "Schönbrunn Palace early before the crowds, a proper coffee house for breakfast, an evening concert or opera — that is Vienna at its best. Don't try to see everything at once.",
    premiumIntroDe: "Wien funktioniert am besten im Rhythmus: Morgen für Museen und Cafes, Nachmittag für Viertel und Spaziergänge, Abend für Konzerte und Restaurants. Wer das zulässt statt zu hetzen, erlebt die Stadt komplett anders.",
    premiumIntroEn: "Vienna works best in rhythm: mornings for museums and coffee houses, afternoons for neighborhoods and walks, evenings for concerts and restaurants. Letting the city breathe instead of rushing through it changes everything.",
    mustSeeDe: ["Schönbrunn früh morgens", "Kaffeehausstunde im Café Central oder Landtmann", "Naschmarkt am Samstag"],
    mustSeeEn: ["Schönbrunn early in the morning", "Coffee house hour at Café Central or Landtmann", "Naschmarkt on a Saturday"],
    stayAreasDe: ["Neubau für Cafes und kurze Wege", "Mariahilf für bezahlbare Lage nahe der City", "Innere Stadt für maximale Nähe — aber Preis beachten"],
    stayAreasEn: ["Neubau for cafes and short distances", "Mariahilf for affordable access to the centre", "Innere Stadt for maximum proximity — but watch the price"],
    timingDe: "Opernball-Wochenende, Adventmärkte und internationale Kongresse lassen die Preise in Wien stark anziehen. Unter der Woche und außerhalb dieser Peaks gibt es oft deutlich bessere Raten.",
    timingEn: "The Opera Ball weekend, Christmas markets and international congresses push Vienna prices hard. Midweek stays and periods outside these peaks often offer significantly better rates.",
  },
  prag: {
    highlightsDe: ["Altstadt", "Mala Strana", "Karlsbrücke am frühen Morgen"],
    highlightsEn: ["Old Town", "Mala Strana", "Charles Bridge early in the morning"],
    stayTipDe: "Prag ist kompakt — du kannst etwas außerhalb der vollsten Touristenzonen wohnen und bist trotzdem in Minuten überall. Vinohrady und Žižkov sind gute Alternativen zur überteuerten Altstadt-Hotellage.",
    stayTipEn: "Prague is compact — you can stay a bit outside the busiest tourist zones and still reach everything in minutes. Vinohrady and Žižkov are solid alternatives to overpriced Old Town locations.",
    savingTipDe: "Prag reagiert sehr stark auf Wochenenden, Feiertage und Hochsommer. Unter der Woche und im Frühjahr oder Herbst sind die Preise oft dramatisch besser. Frühbucher sollten Preisalarme setzen.",
    savingTipEn: "Prague reacts very strongly to weekends, holidays and high summer. Midweek stays in spring or autumn often show dramatically better prices. Early bookers should definitely set price alerts.",
    travelNoteDe: "Die Karlsbrücke um 6 Uhr morgens ohne Touristenmassen, ein Spaziergang durch Mala Strana und abends ein ruhiges Restaurant in Vinohrady statt einem Touristenlokal — so merkt man, was Prag wirklich ausmacht.",
    travelNoteEn: "Charles Bridge at 6am without the crowds, a walk through Mala Strana, and a quiet dinner in Vinohrady instead of a tourist trap — that is when you understand what Prague is really about.",
    premiumIntroDe: "Prag wird oft unterschätzt, weil die Oberfläche so touristisch ist. Wer sich eine Stunde von den Hauptströmen entfernt — in Vinohrady, Žižkov oder am frühen Morgen auf der Karlsbrücke — erlebt eine komplett andere, sehr schöne Stadt.",
    premiumIntroEn: "Prague is often underestimated because the surface looks so touristy. Move an hour away from the main flows — into Vinohrady, Žižkov or onto Charles Bridge early in the morning — and you find a completely different, very beautiful city.",
    mustSeeDe: ["Karlsbrücke vor 7 Uhr morgens", "Abend in Vinohrady oder Žižkov", "Vyšehrad statt Burgberg für Ruhe und Aussicht"],
    mustSeeEn: ["Charles Bridge before 7am", "An evening in Vinohrady or Žižkov", "Vyšehrad instead of the castle hill for peace and views"],
    stayAreasDe: ["Vinohrady für Atmosphäre und Ruhe", "Altstadt nur wenn Lage entscheidend", "Žižkov für einen authentischeren Eindruck"],
    stayAreasEn: ["Vinohrady for atmosphere and calm", "Old Town only when location is critical", "Žižkov for a more authentic feel"],
    timingDe: "Prager Preise springen an Wochenenden, Oster- und Pfingstferien sowie im Juli/August. Herbst und Frühling unter der Woche sind die interessantesten Fenster für Preisalarme.",
    timingEn: "Prague prices jump on weekends, Easter and Whitsun holidays and in July/August. Autumn and spring midweek are the most interesting windows for price alerts.",
  },
  lissabon: {
    highlightsDe: ["Alfama", "Bairro Alto", "Belém"],
    highlightsEn: ["Alfama", "Bairro Alto", "Belém"],
    stayTipDe: "Lissabon ist hügelig — das klingt romantisch, kostet aber jeden Tag Energie. Chiado oder Príncipe Real geben dir schöne Lagen ohne die härtesten Steigungen. Alfama ist atmosphärisch, aber täglich auf und ab zu laufen wird schnell anstrengend.",
    stayTipEn: "Lisbon is hilly — that sounds romantic but costs energy every day. Chiado or Príncipe Real give you beautiful locations without the toughest climbs. Alfama is atmospheric but walking up and down daily gets tiring fast.",
    savingTipDe: "Lissabon hat sich in den letzten Jahren stark verteuert. Sommer, Ostern, lange Wochenenden und Konferenzen lassen die Preise springen. Gerade bei früh gebuchten Aufenthalten lohnt sich tägliches Monitoring bis kurz vor Anreise.",
    savingTipEn: "Lisbon has become significantly pricier in recent years. Summer, Easter, long weekends and conferences push prices sharply. For early bookings, daily monitoring right up until arrival often pays off.",
    travelNoteDe: "Miradouros beim Sonnenuntergang, eine echte Pasteis de Belém direkt beim Kloster, die Tram 28 einmal durch Alfama und ein langer Abend in Bairro Alto — das ist der Lissabon-Rhythmus, der hängen bleibt.",
    travelNoteEn: "Miradouros at sunset, a real pastéis de Belém right at the monastery, tram 28 once through Alfama and a long evening in Bairro Alto — that is the Lisbon rhythm that stays with you.",
    premiumIntroDe: "Lissabon ist eine Stadt der Kontraste zwischen lebendig und melancholisch, hektisch und still. Das Beste entsteht, wenn du Tageszeiten und Viertel bewusst mischst statt ein starres Programm abzuarbeiten.",
    premiumIntroEn: "Lisbon is a city of contrast between lively and melancholic, hectic and still. The best experience comes from consciously mixing times of day and neighborhoods instead of working through a rigid itinerary.",
    mustSeeDe: ["Miradouro da Graça beim Sonnenuntergang", "Pastéis de Belém direkt am Kloster", "Fado-Abend in Alfama statt im Touristenrestaurant"],
    mustSeeEn: ["Miradouro da Graça at sunset", "Pastéis de Belém right at the monastery", "Fado evening in Alfama instead of a tourist restaurant"],
    stayAreasDe: ["Chiado für Cafes und kurze Wege", "Príncipe Real für ruhigere, schöne Lage", "Mouraria für authentisches Flair nahe Alfama"],
    stayAreasEn: ["Chiado for cafes and short distances", "Príncipe Real for a calmer, beautiful location", "Mouraria for an authentic feel close to Alfama"],
    timingDe: "Juni bis August ist teuer und voll. Mai, September und Oktober sind oft das beste Fenster — angenehme Temperaturen und merklich niedrigere Hotelpreise. Wer früh bucht, sollte diese Peaks genau im Blick behalten.",
    timingEn: "June to August is expensive and crowded. May, September and October are often the best window — pleasant temperatures and noticeably lower hotel prices. Early bookers should track these peaks closely.",
  },
  dubai: {
    highlightsDe: ["Downtown", "Dubai Marina", "Al Fahidi"],
    highlightsEn: ["Downtown", "Dubai Marina", "Al Fahidi"],
    stayTipDe: "Dubai ist sehr weitläufig — Lage entscheidet hier darüber, wie viel Zeit und Geld du für Taxis ausgibst. Downtown ist teuer, aber zentral. Dubai Marina ist gut für Strandnähe. Business Bay bietet oft das beste Verhältnis aus Lage und Preis.",
    stayTipEn: "Dubai is very spread out — location determines how much time and money you spend on taxis. Downtown is expensive but central. Dubai Marina is good for beach access. Business Bay often offers the best balance of location and price.",
    savingTipDe: "Dubai-Hotels schwanken extrem saisonal: Oktober bis März ist High Season (teuer), April bis September ist Hot Season (heiß, aber sehr günstig). Wer im Übergang bucht und flexibel ist, findet oft erheblich bessere Raten.",
    savingTipEn: "Dubai hotels fluctuate extremely seasonally: October to March is high season (expensive), April to September is hot season (hot, but very cheap). Booking in the transition periods with flexibility often reveals significantly better rates.",
    travelNoteDe: "Al Fahidi Historic District für den Kontrast zur Hochglanzfassade, Abra-Fähre über den Creek, Abend in der Marina mit Blick auf die Skyline und ein Morgen in der Wüste — das macht Dubai zu einer echten Reise statt nur einem Luxushotel-Erlebnis.",
    travelNoteEn: "Al Fahidi Historic District for contrast against the glossy façade, an abra ferry across the Creek, evening in the Marina overlooking the skyline and a morning in the desert — that turns Dubai into a real trip instead of just a luxury hotel experience.",
    premiumIntroDe: "Dubai lohnt sich am meisten, wenn du aktiv zwischen den Welten wechselst: alte Souks, moderne Skyline, Wüste, Strand. Nur in der Mall und im Hotel zu sitzen ist das teuerste und langweiligste Dubai, das du buchen kannst.",
    premiumIntroEn: "Dubai rewards most when you actively move between worlds: old souks, modern skyline, desert, beach. Staying only in malls and hotels is the most expensive and least interesting version of Dubai you can book.",
    mustSeeDe: ["Al Fahidi Historic District und Abra-Fähre", "Burj Khalifa bei Sonnenuntergang (früh buchen)", "Wüstensafari oder Morgen im Desert Conservation Reserve"],
    mustSeeEn: ["Al Fahidi Historic District and abra ferry", "Burj Khalifa at sunset (book early)", "Desert safari or a morning in the Desert Conservation Reserve"],
    stayAreasDe: ["Downtown für alles aus einer Lage", "Business Bay für gutes Preis-Lage-Verhältnis", "Dubai Marina für Strandnähe und Abendleben"],
    stayAreasEn: ["Downtown for access to everything", "Business Bay for good price-to-location ratio", "Dubai Marina for beach access and evening life"],
    timingDe: "November bis Februar ist teuer und angenehm kühl. September und Oktober sind die besten Übergangsmonate — schon erträglicher und deutlich günstiger. Wer im Sommer bucht, zahlt wenig, schwitzt aber erheblich.",
    timingEn: "November to February is expensive and pleasantly cool. September and October are the best transition months — already manageable and significantly cheaper. Summer bookings are cheap but seriously hot.",
  },
  "new-york": {
    highlightsDe: ["West Village", "Central Park", "Brooklyn Heights"],
    highlightsEn: ["West Village", "Central Park", "Brooklyn Heights"],
    stayTipDe: "In New York ist Lage und U-Bahn-Anbindung wichtiger als Sternekategorie. Midtown Manhattan ist zentral, aber oft teuer und wenig atmosphärisch. Soho, West Village oder Chelsea geben dir besseres Stadtgefühl zu oft vergleichbaren Preisen.",
    stayTipEn: "In New York location and subway access matter more than star rating. Midtown Manhattan is central but often expensive and low on atmosphere. SoHo, West Village or Chelsea give you a better city feel at often comparable prices.",
    savingTipDe: "New York ist eine der preissensitivsten Städte weltweit. Thanksgiving-Wochenende, Silvester, Marathon und Fashion Week lassen Preise explodieren. Frühbucher sollten diese Daten kennen und Preisalarme aktiv nutzen.",
    savingTipEn: "New York is one of the most price-sensitive cities in the world. Thanksgiving weekend, New Year's Eve, the marathon and Fashion Week send prices through the roof. Early bookers need to know these dates and actively use price alerts.",
    travelNoteDe: "Morgens durch Central Park laufen, Mittagessen in einem Stadtviertel statt in einem Touristenlokal, Brooklyn Bridge zu Fuß überqueren und abends ins West Village — das ist New York ohne das übliche Abhaklisten-Programm.",
    travelNoteEn: "Morning run through Central Park, lunch in a real neighborhood instead of a tourist spot, walking the Brooklyn Bridge and an evening in West Village — that is New York without the usual checklist program.",
    premiumIntroDe: "New York wirkt am besten, wenn du dich konsequent in einem Viertel verlierst statt täglich durch die ganze Stadt zu hetzen. Die besten Stunden entstehen oft zufällig — an einer Ecke, in einem Deli, auf einer Bank im Park.",
    premiumIntroEn: "New York works best when you deliberately lose yourself in one neighborhood instead of rushing across the whole city every day. The best moments often happen by accident — on a corner, in a deli, on a bench in the park.",
    mustSeeDe: ["Central Park an einem Werktag morgens", "Brooklyn Heights Promenade beim Sonnenuntergang", "Abend im West Village oder Lower East Side"],
    mustSeeEn: ["Central Park on a weekday morning", "Brooklyn Heights Promenade at sunset", "An evening in West Village or Lower East Side"],
    stayAreasDe: ["Soho und Tribeca für Atmosphäre", "Midtown nur wenn Business oder Theaterbesuch im Fokus", "Brooklyn Heights für ruhigere, günstigere Alternative mit Skyline-Blick"],
    stayAreasEn: ["SoHo and Tribeca for atmosphere", "Midtown only if business or Broadway is the focus", "Brooklyn Heights for a calmer, often cheaper alternative with skyline views"],
    timingDe: "Thanksgiving, Silvester und der NYC Marathon sind die teuersten Tage des Jahres. Januar und Februar sind oft die günstigsten Monate. Frühling und Herbst bieten den besten Kompromiss aus Wetter und Preis.",
    timingEn: "Thanksgiving, New Year's Eve and the NYC Marathon are the most expensive days of the year. January and February are often the cheapest months. Spring and autumn offer the best compromise of weather and price.",
  },
  budapest: {
    highlightsDe: ["Budaer Burg", "Széchenyi-Thermalbad", "Jüdisches Viertel"],
    highlightsEn: ["Buda Castle", "Széchenyi Thermal Bath", "Jewish Quarter"],
    stayTipDe: "Pest-Seite ist für die meisten Reisenden die bessere Wahl: bessere Anbindung, mehr Restaurants und Cafes, günstigere Preise. Die Burg auf der Buda-Seite ist für den Tagesausflug ideal, aber als Hotelstandort eher isoliert.",
    stayTipEn: "The Pest side is the better choice for most travellers: better connections, more restaurants and cafes, lower prices. The Buda Castle area is ideal for a day trip but isolated as a hotel base.",
    savingTipDe: "Budapest hat sich verteuert, ist aber im Vergleich zu Wien oder Paris noch interessant. Wochenenden, Feiertage, Formel-1-Wochenende und Sziget Festival lassen die Preise stark steigen. Wer flexibel bucht, sollte Preisalarme nutzen.",
    savingTipEn: "Budapest has gotten pricier but still offers good value compared to Vienna or Paris. Weekends, holidays, the Formula 1 weekend and Sziget Festival push prices strongly. Flexible bookers should use price alerts.",
    travelNoteDe: "Széchenyi-Bad am Morgen wenn es noch ruhig ist, Mittagessen im Jüdischen Viertel, Abend auf einer Ruin-Bar — das ist Budapest in drei Stationen, die sich wirklich unterscheiden.",
    travelNoteEn: "Széchenyi Baths in the morning before it gets busy, lunch in the Jewish Quarter, evening in a ruin bar — that is Budapest in three stops that genuinely feel different from each other.",
    premiumIntroDe: "Budapest ist eine der wenigen europäischen Städte, die noch echte Entdeckungen bieten — wenn du dich jenseits der Donaupromenade bewegst. Das Jüdische Viertel, die Ruin-Bars und die Kaffeehauskultur erzählen mehr über die Stadt als jede Aussichtsplattform.",
    premiumIntroEn: "Budapest is one of the few European cities that still offers genuine discoveries — if you move beyond the Danube promenade. The Jewish Quarter, the ruin bars and the coffee house culture tell more about the city than any viewpoint.",
    mustSeeDe: ["Széchenyi-Bad früh morgens oder am Abend", "Abend in einer Ruin-Bar (Szimpla Kert)", "Fischerbastei bei Sonnenaufgang statt tagsüber"],
    mustSeeEn: ["Széchenyi Baths early in the morning or evening", "Evening in a ruin bar (Szimpla Kert)", "Fisherman's Bastion at sunrise instead of midday"],
    stayAreasDe: ["Belváros für klassische Stadtlage", "Erzsébetváros (Jüdisches Viertel) für Atmosphäre", "Terézváros für ruhigere, gute Lage nahe der Andrássy út"],
    stayAreasEn: ["Belváros for classic central location", "Erzsébetváros (Jewish Quarter) for atmosphere", "Terézváros for a calmer, well-located stay near Andrássy út"],
    timingDe: "Formel-1-Rennwochenende und Sziget Festival machen Budapest kurzzeitig so teuer wie Paris. Außerhalb dieser Events sind die Preise meist sehr attraktiv. Frühling und Herbst unter der Woche sind die besten Fenster.",
    timingEn: "The Formula 1 race weekend and Sziget Festival make Budapest briefly as expensive as Paris. Outside these events, prices are usually very attractive. Spring and autumn midweek are the best windows.",
  },
  bali: {
    highlightsDe: ["Ubud", "Canggu", "Uluwatu"],
    highlightsEn: ["Ubud", "Canggu", "Uluwatu"],
    stayTipDe: "Bali ist kein Stadttrip — du buchst eine Atmosphäre, keine Lage. Ubud ist für Ruhe, Natur und Kultur. Canggu für Surfen, Cafes und junges Flair. Seminyak für Strand und Komfort. Uluwatu für Klippen, Sonnenuntergänge und Surfen. Entscheide das zuerst, bevor du Hotel-Preise vergleichst.",
    stayTipEn: "Bali is not a city trip — you are booking an atmosphere, not a location. Ubud for calm, nature and culture. Canggu for surfing, cafes and a younger vibe. Seminyak for beach and comfort. Uluwatu for cliffs, sunsets and surfing. Decide that first before comparing hotel prices.",
    savingTipDe: "Bali-Resorts schwanken stark mit Saison und Auslastung. Hochsommer und Weihnachten/Silvester sind sehr teuer. Schulterzeit (Mai/Juni und September/Oktober) gibt dir gutes Wetter zu deutlich besseren Preisen. Bei Resorts mit mehreren Nächten summieren sich Preisunterschiede schnell.",
    savingTipEn: "Bali resorts fluctuate strongly with season and occupancy. High summer and Christmas/New Year are very expensive. Shoulder season (May/June and September/October) gives you good weather at much better prices. For multi-night resort stays, price differences add up quickly.",
    travelNoteDe: "Reisterrassen in Tegallalang früh morgens, Tempel bei Sonnenuntergang in Uluwatu, ein Tag nur Ubud und nichts planen — das ist Bali in seiner ehrlichsten Form.",
    travelNoteEn: "Tegallalang rice terraces early in the morning, Uluwatu temple at sunset, one full day in Ubud with nothing planned — that is Bali in its most honest form.",
    premiumIntroDe: "Bali ist am besten, wenn du nicht zu viel planst. Die Insel belohnt Entschleunigung — wer jeden Tag ein neues Gebiet ansteuert, verpasst genau das, was Bali ausmacht: Atmosphäre, Ruhe und die kleinen Rituale des Alltags.",
    premiumIntroEn: "Bali is at its best when you do not plan too much. The island rewards slowing down — if you rush to a different area every day, you miss exactly what makes Bali special: atmosphere, calm and the small rituals of daily life.",
    mustSeeDe: ["Tegallalang Reisterrassen früh morgens", "Sonnenuntergang am Uluwatu-Tempel mit Kecak-Tanz", "Ein halber Tag nur in Ubud ohne festes Programm"],
    mustSeeEn: ["Tegallalang rice terraces early in the morning", "Sunset at Uluwatu Temple with Kecak dance", "Half a day in Ubud with no fixed plans"],
    stayAreasDe: ["Ubud für Natur und Ruhe", "Seminyak für Strand und Komfort", "Canggu für Surfen und junges Flair", "Uluwatu für spektakuläre Klippen-Lage"],
    stayAreasEn: ["Ubud for nature and calm", "Seminyak for beach and comfort", "Canggu for surfing and a younger vibe", "Uluwatu for spectacular cliff-side location"],
    timingDe: "Juli/August und Weihnachten/Silvester sind die teuersten Perioden. Mai, Juni und September sind der Sweet Spot: kaum Regen, deutlich weniger Massen und merklich bessere Hotelpreise.",
    timingEn: "July/August and Christmas/New Year are the most expensive periods. May, June and September are the sweet spot: little rain, far fewer crowds and noticeably better hotel prices.",
  },
  mallorca: {
    highlightsDe: ["Palma Altstadt", "Serra de Tramuntana", "Nordk\u00fcste"],
    highlightsEn: ["Palma Old Town", "Serra de Tramuntana", "North Coast"],
    stayTipDe: "Palma ist für die meisten der beste Ausgangspunkt: Altstadt, Restaurants und Strand in Reichweite. Wer in ein Resort im Süden oder Norden bucht, ist günstiger, aber braucht ein Auto für alles. Entscheide das bewusst.",
    stayTipEn: "Palma is the best base for most travellers: old town, restaurants and beach within reach. Booking a resort in the south or north is cheaper but requires a car for everything. Make that choice consciously.",
    savingTipDe: "Mallorca hat eine sehr klare Saisonkurve: Juli/August ist extrem teuer, Mai/Juni und September/Oktober sind der Sweet Spot für Preis und Wetter. Wer früh für den Sommer bucht, sollte unbedingt Preisalarme setzen.",
    savingTipEn: "Mallorca has a very clear seasonal curve: July/August is extremely expensive, May/June and September/October are the sweet spot for price and weather. If you book early for summer, definitely set price alerts.",
    travelNoteDe: "Palma-Altstadt am frühen Morgen ohne Massen, Fischmarkt, ein Tag an einem ruhigeren Strand im Norden und Abends Tapas in einer der kleinen Gassen — das ist Mallorca jenseits der All-inclusive-Resort-Logik.",
    travelNoteEn: "Palma old town in the early morning without crowds, fish market, one day at a quieter beach in the north and tapas in the narrow lanes in the evening — that is Mallorca beyond all-inclusive resort logic.",
    premiumIntroDe: "Mallorca hat zwei Gesichter: das Resort-Mallorca mit Pool und All-Inclusive, und das echte Mallorca mit Olivenhainen, alten Dörfern und stillen Buchten. Beide sind legitim — aber nur eines davon hinterlässt wirklich einen Eindruck.",
    premiumIntroEn: "Mallorca has two faces: resort Mallorca with pools and all-inclusive, and real Mallorca with olive groves, old villages and quiet coves. Both are legitimate — but only one of them genuinely stays with you.",
    mustSeeDe: ["Valldemossa und Deiá in der Serra de Tramuntana", "Palma Altstadt früh morgens", "Eine der stillen Calas im Norden — Cala Mesquida oder Cala Agulla"],
    mustSeeEn: ["Valldemossa and Deiá in the Serra de Tramuntana", "Palma old town early morning", "One of the quiet coves in the north — Cala Mesquida or Cala Agulla"],
    stayAreasDe: ["Palma für Stadtgefühl und gute Basis", "Pollença im Norden für Ruhe und Landschaft", "Alcúdia für Strandnähe mit etwas weniger Massentourismus"],
    stayAreasEn: ["Palma for city feel and a strong base", "Pollença in the north for calm and scenery", "Alcúdia for beach access with slightly less mass tourism"],
    timingDe: "August ist der teuerste Monat — sehr voll und sehr teuer. Mai und Oktober sind klimatisch fast genauso gut bei deutlich niedrigeren Preisen. Wer im Sommer bucht, sollte früh buchen und Alarme setzen.",
    timingEn: "August is the most expensive month — very crowded and very costly. May and October are climatically almost as good at significantly lower prices. Summer bookers should book early and set alerts.",
  },
  teneriffa: {
    highlightsDe: ["Teide-Nationalpark", "La Laguna", "Costa Adeje"],
    highlightsEn: ["Teide National Park", "La Laguna", "Costa Adeje"],
    stayTipDe: "Teneriffa hat zwei komplett verschiedene Gesichter: Der Süden (Costa Adeje, Los Cristianos) ist sonniger, trockener und voll mit Resorts. Der Norden (Puerto de la Cruz, La Orotava) ist grüner, authentischer und günstiger. Entscheide das bewusst — der falsche Teil der Insel kann einen Trip ruinieren.",
    stayTipEn: "Tenerife has two completely different faces: the south (Costa Adeje, Los Cristianos) is sunnier, drier and full of resorts. The north (Puerto de la Cruz, La Orotava) is greener, more authentic and cheaper. Choose consciously — the wrong part of the island can ruin a trip.",
    savingTipDe: "Teneriffa ist ganzjährig beliebt, was Preise konstant hält. Die stärksten Schwankungen gibt es zu Weihnachten/Silvester, Karneval und deutschen Schulferien. Bei längeren Aufenthalten und Familienhotels summieren sich Preisunterschiede schnell auf mehrere hundert Euro.",
    savingTipEn: "Tenerife is popular year-round, which keeps prices fairly stable. The strongest fluctuations come at Christmas/New Year, Carnival and German school holiday periods. For longer stays and family hotels, price differences quickly add up to several hundred euros.",
    travelNoteDe: "Teide bei Sonnenaufgang mit Seilbahn (Tickets Wochen im Voraus buchen), ein Tag in La Laguna zwischen Kolonialhäusern und Cafes und ein ruhiger Strand abseits der Haupthotels — das ist Teneriffa in drei Erlebnissen.",
    travelNoteEn: "Teide at sunrise by cable car (book tickets weeks in advance), a day in La Laguna between colonial houses and cafes, and a quiet beach away from the main hotels — that is Tenerife in three experiences.",
    premiumIntroDe: "Teneriffa ist mehr als Poolkante und Piña Colada — aber du musst aktiv aus dem Resort herausgehen. Der Teide, die Anaga-Berge und La Laguna sind echte Naturerlebnisse auf einer Insel, die viele nur als Sonnendeck kennen.",
    premiumIntroEn: "Tenerife is more than poolside and piña coladas — but you have to actively step out of the resort. The Teide, the Anaga mountains and La Laguna are genuine nature experiences on an island most people only know as a sun deck.",
    mustSeeDe: ["Teide-Nationalpark früh morgens", "La Laguna Altstadt (UNESCO)", "Masca-Schlucht für Wanderer"],
    mustSeeEn: ["Teide National Park early in the morning", "La Laguna old town (UNESCO)", "Masca gorge for hikers"],
    stayAreasDe: ["Costa Adeje für Strandkomfort und Sonne", "Puerto de la Cruz für authentischeres Erlebnis", "La Orotava für Ruhe und Nähe zum Teide"],
    stayAreasEn: ["Costa Adeje for beach comfort and sun", "Puerto de la Cruz for a more authentic experience", "La Orotava for calm and proximity to Teide"],
    timingDe: "Dezember bis Februar ist High Season für Nordeuropäer auf der Flucht vor dem Winter — teuer und voll. März bis Mai und Oktober/November sind oft die besten Fenster für Preis und Wetter gleichzeitig.",
    timingEn: "December to February is high season for Northern Europeans escaping winter — expensive and crowded. March to May and October/November are often the best windows for price and weather combined.",
  },
  zuerich: {
    highlightsDe: ["Altstadt (Lindenhügel)", "Seepromenade", "Zürich West"],
    highlightsEn: ["Old Town (Lindenhügel)", "Lake Promenade", "Zurich West"],
    stayTipDe: "Zürich ist sehr kompakt — fast alle Lagen funktionieren gut. Zentrale Hotels nahe Hauptbahnhof oder Altstadt sind am bequemsten, aber auch am teuersten. Zürich West ist eine günstigere Alternative mit eigenem Flair.",
    stayTipEn: "Zurich is very compact — almost all locations work well. Central hotels near the main station or old town are most convenient but also most expensive. Zurich West is a cheaper alternative with its own character.",
    savingTipDe: "Zürich ist eine der teuersten Städte der Welt — schon kleine Preisunterschiede bei Hotels bedeuten hier echtes Geld. Kongresse, Messen und Events auf dem Messeplatz lassen die Preise stark steigen. Selbst bei kurzem Aufenthalt lohnt sich Monitoring.",
    savingTipEn: "Zurich is one of the most expensive cities in the world — even small hotel price differences mean real money here. Congresses, trade fairs and events at the Messe push prices strongly. Even for short stays, monitoring pays off.",
    travelNoteDe: "Seepromenade am Abend, Altstadt zu Fuß von beiden Uferseiten und ein Nachmittag in Zürich West mit seinen umgebauten Industriehallen — das ist ein sehr guter erster Zürich-Tag.",
    travelNoteEn: "Lake promenade in the evening, old town on foot from both sides of the river and an afternoon in Zurich West with its converted industrial spaces — that makes for a very good first day in Zurich.",
    premiumIntroDe: "Zürich überrascht viele, weil die Stadt kleiner und entspannter wirkt als erwartet. Der Limmat, die kleinen Gassen und das Seeufer erzählen mehr über die Stadtqualität als die Bankentürme. Wer genug Zeit mitbringt, findet hier eine sehr lebendige, sehr selbstbewusste Stadt.",
    premiumIntroEn: "Zurich surprises many because it feels smaller and calmer than expected. The Limmat river, the small lanes and the lake shore tell more about the city's quality than the banking towers. With enough time, you find a very lively, very self-confident city.",
    mustSeeDe: ["Abend an der Seepromenade beim Sonnenuntergang", "Zürich West — Viadukt und Langstrasse", "Altstadt von beiden Seiten der Limmat"],
    mustSeeEn: ["Evening on the lake promenade at sunset", "Zurich West — Viadukt and Langstrasse", "Old town from both sides of the Limmat"],
    stayAreasDe: ["City 1 (Altstadt) für klassische Lage", "Zürich West (4./5. Kreis) für günstigere, lebendige Alternative", "Kreis 6 oder 7 für ruhigere Wohnlagen"],
    stayAreasEn: ["City 1 (Altstadt) for classic location", "Zurich West (districts 4/5) for a cheaper, livelier alternative", "Districts 6 or 7 for quieter residential locations"],
    timingDe: "Messetermine (Art Basel, SIHH, Swiss Indoors) lassen Zürich-Hotelpreise in kurzer Zeit deutlich steigen. Außerhalb dieser Termine und im Winter sind die Preise oft merklich besser.",
    timingEn: "Trade fair dates (Art Basel, SIHH, Swiss Indoors) can push Zurich hotel prices sharply in a short time. Outside these events and in winter, prices are often noticeably better.",
  },
  venedig: {
    highlightsDe: ["Cannaregio", "Dorsoduro", "Lagunenblick am frühen Morgen"],
    highlightsEn: ["Cannaregio", "Dorsoduro", "Lagoon views early in the morning"],
    stayTipDe: "In Venedig ist Mikro-Lage fast alles. Direkt am Markusplatz oder Rialto zu wohnen ist teuer und laut. Cannaregio oder Dorsoduro geben dir echtes Stadtflair bei deutlich ruhigeren Gassen und oft niedrigeren Preisen.",
    stayTipEn: "In Venice, micro-location is almost everything. Staying right on St Mark's Square or Rialto is expensive and noisy. Cannaregio or Dorsoduro give you genuine city atmosphere with much quieter lanes and often lower prices.",
    savingTipDe: "Venedig hat Karneval (extrem teuer), Biennale-Perioden, Feiertage und Hochsommer als ausgeprägte Preispeaks. Außerhalb dieser Fenster kann Venedig überraschend günstig sein — genau deshalb lohnen sich Preisalarme nach einer frühen Buchung.",
    savingTipEn: "Venice has Carnival (extremely expensive), Biennale periods, holidays and high summer as clear price peaks. Outside these windows Venice can be surprisingly affordable — exactly why price alerts after an early booking make sense.",
    travelNoteDe: "Venedig vor 7 Uhr morgens ist eine andere Stadt — stille Gassen, keine Kreuzfahrtpassagiere, nur das Rauschen des Wassers. Wer einmal so durch Cannaregio läuft, versteht, warum diese Stadt einzigartig ist.",
    travelNoteEn: "Venice before 7am is a different city — silent lanes, no cruise passengers, only the sound of water. Walking through Cannaregio like that once makes you understand why this city is unique.",
    premiumIntroDe: "Venedig ist die einzige Stadt, in der schlechtes Hotel-Timing buchstäblich die Erfahrung kaputt machen kann — weil Tageszeiten und Viertel so extrem unterschiedlich wirken. Das Wissen darum ist mehr wert als jeder Reiseführer.",
    premiumIntroEn: "Venice is the only city where bad hotel timing can literally ruin the experience — because time of day and neighborhood differ so extremely. Understanding that is worth more than any travel guide.",
    mustSeeDe: ["Markusplatz vor 7 Uhr morgens", "Abend in Cannaregio oder Dorsoduro ohne Touristenrestaurant", "Vaporetto-Fahrt entlang des Canal Grande bei Sonnenuntergang"],
    mustSeeEn: ["St Mark's Square before 7am", "Evening in Cannaregio or Dorsoduro without tourist restaurants", "Vaporetto ride along the Grand Canal at sunset"],
    stayAreasDe: ["Cannaregio für authentisches Viertelgefühl", "Dorsoduro für ruhige, schöne Lage", "San Polo für zentrale Lage mit weniger Massentourismus"],
    stayAreasEn: ["Cannaregio for authentic neighborhood feel", "Dorsoduro for a calm, beautiful location", "San Polo for central location with less mass tourism"],
    timingDe: "Karneval ist das absolute Preismaximum — Hotelpreise können sich verdoppeln oder verdreifachen. November und Januar sind oft günstig und atmosphärisch ruhig, aber neblig. Frühling und Frühherbst sind der beste Kompromiss.",
    timingEn: "Carnival is the absolute price peak — hotel prices can double or triple. November and January are often cheap and atmospherically quiet, but foggy. Spring and early autumn are the best compromise.",
  },
  florenz: {
    highlightsDe: ["Duomo", "Oltrarno", "Piazzale Michelangelo"],
    highlightsEn: ["Duomo", "Oltrarno", "Piazzale Michelangelo"],
    stayTipDe: "Florenz ist kompakt und gut zu Fuß — eine gute Lage im historischen Zentrum oder in Oltrarno gibt dir kurze Wege zu allem Wichtigen. Hotels nahe dem Duomo sind oft überteuert. San Frediano (Oltrarno) ist eine schöne, günstigere Alternative.",
    stayTipEn: "Florence is compact and very walkable — a good location in the historic centre or Oltrarno gives you short distances to everything important. Hotels near the Duomo are often overpriced. San Frediano in Oltrarno is a beautiful, cheaper alternative.",
    savingTipDe: "Florenz hat im Frühling (April/Mai) und Herbst (September/Oktober) die stärksten Preisbewegungen — wegen Massentourismus und internationaler Reisegruppen. Wer früh bucht, sollte diese Perioden aktiv mit Preisalarmen beobachten.",
    savingTipEn: "Florence has the strongest price movements in spring (April/May) and autumn (September/October) due to mass tourism and international travel groups. Early bookers should actively monitor these periods with price alerts.",
    travelNoteDe: "Piazzale Michelangelo beim Sonnenaufgang statt Sonnenuntergang (weniger Massen), Oltrarno zu Fuß mit kleinen Ateliers und Restaurants, ein halber Tag nur für die Uffizien mit vorab gebuchten Tickets — das ist Florenz ohne das schlimmste Gedränge.",
    travelNoteEn: "Piazzale Michelangelo at sunrise instead of sunset (fewer crowds), Oltrarno on foot with small workshops and restaurants, half a day dedicated to the Uffizi with pre-booked tickets — that is Florence without the worst of the crowds.",
    premiumIntroDe: "Florenz ist im Kern eine kleine Stadt — aber mit einer der dichtesten Kunstsammlungen der Welt. Das Problem ist, dass die meisten Besucher versuchen, zu viel auf einmal zu sehen. Weniger Museen, mehr Stadtviertel, ist fast immer die bessere Entscheidung.",
    premiumIntroEn: "Florence is at its core a small city — but with one of the densest art collections in the world. The problem is that most visitors try to see too much at once. Fewer museums, more neighbourhood wandering is almost always the better choice.",
    mustSeeDe: ["Piazzale Michelangelo beim Sonnenaufgang", "Oltrarno — Borgo San Frediano und die kleinen Ateliers", "Uffizien mit vorab gebuchten Tickets (niemals ohne)"],
    mustSeeEn: ["Piazzale Michelangelo at sunrise", "Oltrarno — Borgo San Frediano and the small workshops", "Uffizi with pre-booked tickets (never without)"],
    stayAreasDe: ["Oltrarno (San Frediano) für Atmosphäre und etwas niedrigere Preise", "Santa Croce für zentrale Lage und lebendige Gassen", "Santa Maria Novella für gute Anbindung nahe Bahnhof"],
    stayAreasEn: ["Oltrarno (San Frediano) for atmosphere and slightly lower prices", "Santa Croce for central location and lively lanes", "Santa Maria Novella for good connections near the station"],
    timingDe: "April bis Juni und September/Oktober sind Hochsaison — schön, aber teuer und voll. Januar/Februar sind ruhig und günstig. Wer im Frühjahr früh gebucht hat, sollte unbedingt Preisalarme nutzen.",
    timingEn: "April to June and September/October are high season — beautiful but expensive and crowded. January/February are quiet and cheap. If you booked early for spring, definitely use price alerts.",
  },
  madrid: {
    highlightsDe: ["Retiro", "Malasaña", "La Latina"],
    highlightsEn: ["Retiro", "Malasaña", "La Latina"],
    stayTipDe: "Madrid hat keinen schlechten Fleck im Zentrum — Malasaña, Chueca, La Latina und Lavapiés sind alle gut und haben jeweils eigene Charaktere. Malasaña ist lebendig und gut für jüngere Reisende; La Latina ist der klassische Tapas-Abend-Bezirk.",
    stayTipEn: "Madrid has no bad spot in the centre — Malasaña, Chueca, La Latina and Lavapiés all work and each has its own character. Malasaña is lively and good for younger travellers; La Latina is the classic tapas-evening district.",
    savingTipDe: "Real-Madrid-Spiele, Champions-League-Runden und große Konzerte lassen die Preise in Madrid springen. Außerhalb dieser Events sind die Preise oft sehr fair. Wer früh bucht, sollte den Kalender genau kennen.",
    savingTipEn: "Real Madrid matches, Champions League rounds and major concerts push Madrid prices strongly. Outside these events, prices are often very fair. Early bookers should know the calendar well.",
    travelNoteDe: "Das Prado-Museum ohne Zeitdruck, ein langer Tapas-Abend angefangen um 21 Uhr in La Latina, ein Morgen im Retiro und ein Nacht-Aperitivo auf einer Terrasse — das ist Madrids bester Rhythmus.",
    travelNoteEn: "The Prado without time pressure, a long tapas evening starting at 9pm in La Latina, a morning in Retiro and a late-night aperitivo on a terrace — that is Madrid's best rhythm.",
    premiumIntroDe: "Madrid ist die Stadt, in der du am spätesten zu Abend isst, am längsten aufbleibst und trotzdem das Gefühl hast, nichts verpasst zu haben — weil das die Stadt so aufgebaut hat. Wer das zulässt statt zu hetzen, erlebt Madrid komplett.",
    premiumIntroEn: "Madrid is the city where you eat the latest, stay out the longest and still feel like you have not missed anything — because the city is built that way. Letting yourself go with that rhythm instead of rushing through it shows you Madrid completely.",
    mustSeeDe: ["Prado am frühen Morgen (öffnet um 10 Uhr)", "Tapas-Abend in La Latina — Cava Baja", "Retiro Sonntag morgens mit Madrileños"],
    mustSeeEn: ["Prado early in the morning (opens at 10am)", "Tapas evening in La Latina — Cava Baja", "Retiro on a Sunday morning with Madrileños"],
    stayAreasDe: ["Malasaña für Energie und gute Cafes", "La Latina für Tapas und historisches Flair", "Chueca für lebendige, gastfreundliche Atmosphäre"],
    stayAreasEn: ["Malasaña for energy and good cafes", "La Latina for tapas and historic atmosphere", "Chueca for a lively, welcoming atmosphere"],
    timingDe: "Real-Madrid-Heimspiele, Copa-del-Rey-Runden und große Events in der IFEMA machen einzelne Wochenenden extrem teuer. Wer den Kalender nicht kennt und früh bucht, kann bös überrascht werden — Preisalarme helfen hier besonders.",
    timingEn: "Real Madrid home games, Copa del Rey rounds and large events at IFEMA make specific weekends extremely expensive. Not knowing the calendar when booking early can mean nasty surprises — price alerts are especially useful here.",
  },
  athen: {
    highlightsDe: ["Plaka", "Koukaki", "Akropolis-Blickpunkte"],
    highlightsEn: ["Plaka", "Koukaki", "Acropolis viewpoints"],
    stayTipDe: "Koukaki ist für die meisten Athen-Reisenden die beste Wahl: nah an der Akropolis, ruhiger als Plaka, günstiger als Syntagma und mit echten Cafes und Restaurants. Monastiraki ist gut für schnelle Lage, aber laut. Exarchia ist interessant, aber nichts für jeden.",
    stayTipEn: "Koukaki is the best choice for most Athens visitors: close to the Acropolis, quieter than Plaka, cheaper than Syntagma and with real cafes and restaurants. Monastiraki is good for a quick location but noisy. Exarchia is interesting but not for everyone.",
    savingTipDe: "Athen hat sich in den letzten Jahren stark verteuert — besonders im Sommer (Juni–August), wo die Hitze extrem ist, die Preise aber auch. Mai und Oktober sind der Sweet Spot: angenehme Temperaturen und deutlich günstigere Preise.",
    savingTipEn: "Athens has become significantly more expensive in recent years — especially in summer (June–August) when the heat is extreme but so are the prices. May and October are the sweet spot: pleasant temperatures and noticeably lower prices.",
    travelNoteDe: "Akropolis vor 9 Uhr morgens (öffnet 8 Uhr), Mittagspause in Koukaki mit griechischem Kaffee, Abend in Monastiraki mit Blick auf die beleuchtete Akropolis — das ist Athen in seiner besten Tagesstruktur.",
    travelNoteEn: "Acropolis before 9am (opens 8am), midday rest in Koukaki with a Greek coffee, evening in Monastiraki with the illuminated Acropolis in view — that is Athens in its best daily rhythm.",
    premiumIntroDe: "Athen ist mehr als Akropolis und Souvenir-Läden — aber du musst aktiv in die richtigen Viertel gehen. Koukaki, Exarchia und Psirri erzählen eine andere, lebendigere Geschichte als die touristischen Hauptrouten.",
    premiumIntroEn: "Athens is more than the Acropolis and souvenir shops — but you have to actively go to the right neighborhoods. Koukaki, Exarchia and Psirri tell a different, more lively story than the main tourist routes.",
    mustSeeDe: ["Akropolis kurz nach Öffnung (8 Uhr)", "Filopappou-Hügel bei Sonnenuntergang (weniger bekannt als Lycabettus)", "Abend in Monastiraki oder Psirri"],
    mustSeeEn: ["Acropolis shortly after opening (8am)", "Filopappou Hill at sunset (less known than Lycabettus)", "Evening in Monastiraki or Psirri"],
    stayAreasDe: ["Koukaki für die beste Kombination aus Lage und Preis", "Monastiraki für maximale Zentralität", "Mets für ruhige, grüne Wohnlage nahe Akropolis"],
    stayAreasEn: ["Koukaki for the best combination of location and price", "Monastiraki for maximum centrality", "Mets for a quiet, green residential feel close to the Acropolis"],
    timingDe: "Juli und August sind heiß und teuer — bis zu 38°C und Hotelpreise auf Höchstniveau. Mai und Oktober sind fast perfekt: angenehmes Wetter, deutlich weniger Massen und spürbar günstigere Preise.",
    timingEn: "July and August are hot and expensive — up to 38°C and hotel prices at their peak. May and October are almost perfect: pleasant weather, far fewer crowds and noticeably lower prices.",
  },
  istanbul: {
    highlightsDe: ["Sultanahmet", "Beyoğlu", "Bosporus"],
    highlightsEn: ["Sultanahmet", "Beyoğlu", "Bosphorus"],
    stayTipDe: "Istanbul ist eine zweigeteilte Stadt — Sultanahmet für Geschichte, Beyoğlu (Galata, Karaköy) für modernes Stadtleben. Sultanahmet ist toristisch und abends ruhig; Beyoğlu ist lebendiger und besser für Abendkultur. Beides hat seine Logik — aber nicht gemeinsam in einer Reise untergebracht.",
    stayTipEn: "Istanbul is a city in two parts — Sultanahmet for history, Beyoğlu (Galata, Karaköy) for modern city life. Sultanahmet is tourist-heavy and quiet in the evening; Beyoğlu is livelier and better for evening culture. Both make sense — but not crammed into one trip.",
    savingTipDe: "Istanbul hat durch die Lira-Schwäche für westeuropäische Reisende interessante Preise geboten — aber das kann sich ändern. Außerdem reagieren Preise stark auf Feiertage, Ramadan und Events. Preisalarme sind hier sehr sinnvoll.",
    savingTipEn: "Istanbul has offered interesting prices for Western European travellers due to the weak lira — but that can change. Prices also react strongly to holidays, Ramadan and events. Price alerts are very sensible here.",
    travelNoteDe: "Bosporus-Fähre von Karaköy nach Üsküdar für den besten Ausblick und 3 Lira, Gewürzbasar früh morgens, Abend in Karaköy mit Meze und Raki — das ist Istanbul abseits des Standardprogramms.",
    travelNoteEn: "Bosphorus ferry from Karaköy to Üsküdar for the best view and a few lira, Spice Bazaar early in the morning, evening in Karaköy with meze and raki — that is Istanbul beyond the standard itinerary.",
    premiumIntroDe: "Istanbul ist die einzige Stadt, in der du morgens in Europa frühstückst und abends in Asien einen Tee trinkst — und das buchstäblich mit der Fähre in 20 Minuten. Wer das einmal erlebt hat, versteht, warum Istanbul keine normale Stadtreise ist.",
    premiumIntroEn: "Istanbul is the only city where you can have breakfast in Europe and a tea in Asia in the evening — literally by ferry in 20 minutes. Once you experience that, you understand why Istanbul is not a normal city trip.",
    mustSeeDe: ["Hagia Sophia und Blaue Moschee früh morgens (zu verschiedenen Zeiten)", "Bosporus-Fähre nach Üsküdar (Asien-Seite)", "Abend in Karaköy mit Meze und Raki"],
    mustSeeEn: ["Hagia Sophia and Blue Mosque early in the morning (at different times)", "Bosphorus ferry to Üsküdar (Asia side)", "Evening in Karaköy with meze and raki"],
    stayAreasDe: ["Sultanahmet für Geschichtsfokus", "Karaköy/Galata für moderne Stadtlage und Abendleben", "Cihangir für ruhige, kreative Nachbarschaft in Gehdistanz zu beiden Welten"],
    stayAreasEn: ["Sultanahmet for a history focus", "Karaköy/Galata for modern city location and evening life", "Cihangir for a calm, creative neighborhood within walking distance of both worlds"],
    timingDe: "Ramadan verändert den Stadtrhythmus komplett — interessant, aber für Erstbesucher herausfordernd. Sommer ist heiß und teuer. Frühling und Herbst sind fast immer die besten Monate für Wetter und Preise.",
    timingEn: "Ramadan changes the city's rhythm completely — interesting, but challenging for first-time visitors. Summer is hot and expensive. Spring and autumn are almost always the best months for weather and prices.",
  },
};

export function getCityGuide(slug: string): CityGuide | null {
  return cityGuides[slug] ?? null;
}
