export type CityGuide = {
  highlightsDe: string[];
  highlightsEn: string[];
  stayTipDe: string;
  stayTipEn: string;
  savingTipDe: string;
  savingTipEn: string;
  travelNoteDe: string;
  travelNoteEn: string;
  premiumIntroDe?: string;
  premiumIntroEn?: string;
  mustSeeDe?: string[];
  mustSeeEn?: string[];
  stayAreasDe?: string[];
  stayAreasEn?: string[];
  timingDe?: string;
  timingEn?: string;
};

export const cityGuides: Record<string, CityGuide> = {
  amsterdam: {
    highlightsDe: ["Grachtengürtel", "Jordaan", "Museumsviertel"],
    highlightsEn: ["Canal Belt", "Jordaan", "Museum Quarter"],
    stayTipDe: "Wenn du Amsterdam entspannt erleben willst, sind Jordaan, De Pijp oder die Gegend rund um das Museumsviertel oft spannender als nur direkt am Hauptbahnhof.",
    stayTipEn: "If you want a calmer Amsterdam stay, Jordaan, De Pijp and the Museum Quarter are often more rewarding than staying right by the central station.",
    savingTipDe: "Amsterdam wird an Wochenenden, Feiertagen und zu Event-Zeiten schnell teuer. Wer früh flexibel bucht, hat oft später noch gute Chancen auf bessere Raten.",
    savingTipEn: "Amsterdam gets expensive quickly on weekends, holidays and event dates. If you book early with flexibility, you often still have a chance to catch a better rate later.",
    travelNoteDe: "Für einen klassischen Citytrip lohnen sich Bootsfahrten, Museen und Spaziergänge durch die kleineren Viertel mehr als nur die typischen Hotspots.",
    travelNoteEn: "For a classic city trip, canal cruises, museums and wandering through smaller neighborhoods tend to be more rewarding than only ticking off the biggest hotspots.",
    premiumIntroDe: "Amsterdam funktioniert am besten, wenn du Wasser, Viertel und Tempo mitdenkst. Die Stadt wirkt nicht über große Sehenswürdigkeiten, sondern über kleine Straßenzüge, Cafes und den Wechsel zwischen lebendig und ruhig.",
    premiumIntroEn: "Amsterdam works best when you think in terms of water, neighborhoods and rhythm. The city shines less through giant landmarks and more through smaller streets, cafes and the balance between lively and calm.",
    mustSeeDe: ["Frühe Grachtenrunde", "Jordaan am Abend", "Museumsplein ohne Mittagsstress"],
    mustSeeEn: ["Early canal walk", "Jordaan in the evening", "Museumsplein outside midday rush"],
    stayAreasDe: ["Jordaan für Atmosphäre", "De Pijp für Cafes", "Museumsviertel für kurze Wege"],
    stayAreasEn: ["Jordaan for atmosphere", "De Pijp for cafes", "Museum Quarter for walkability"],
    timingDe: "Besonders stark schwanken Preise rund um Fr-So, Feiertage und Eventwochen. Unter der Woche wirkt Amsterdam oft ruhiger und preislich interessanter.",
    timingEn: "Prices move most around Fri-Sun, holidays and event weeks. Midweek Amsterdam is often calmer and more attractive on price.",
  },
  paris: {
    highlightsDe: ["Marais", "Saint-Germain-des-Pres", "Montmartre"],
    highlightsEn: ["Le Marais", "Saint-Germain-des-Pres", "Montmartre"],
    stayTipDe: "Wenn du viel zu Fuß machen willst, sind zentrale Viertel wie Marais oder Saint-Germain oft praktischer als sehr günstige Randlagen.",
    stayTipEn: "If you want to do a lot on foot, central areas like Le Marais or Saint-Germain are often more practical than very cheap outer districts.",
    savingTipDe: "Paris reagiert stark auf Messen, Feiertage und lange Wochenenden. Gerade bei Frühbuchungen lohnt sich Preisüberwachung bis kurz vor Anreise.",
    savingTipEn: "Paris reacts strongly to fairs, holidays and long weekends. Especially with early bookings, price tracking can pay off right up to arrival.",
    travelNoteDe: "Kleine Cafe-Pausen, Spaziergänge an der Seine und ein klarer Plan pro Arrondissement machen den Aufenthalt meist besser als zu viele Programmpunkte.",
    travelNoteEn: "Small cafe breaks, Seine walks and a simple plan per arrondissement often make the trip better than cramming in too many attractions.",
    premiumIntroDe: "Paris wird schnell überladen geplant. Viel schöner wird die Stadt, wenn du einzelne Arrondissements bewusst erlebst: morgens ein Museum, nachmittags ein Viertel, abends gutes Essen statt zehn Haken auf einer Liste.",
    premiumIntroEn: "Paris is often overplanned. It becomes much better when you experience one arrondissement at a time: a museum in the morning, a neighborhood in the afternoon and a strong dinner instead of ten boxes ticked.",
    mustSeeDe: ["Seine-Spaziergang bei Sonnenuntergang", "Marais mit kleinen Boutiquen", "Montmartre früh statt mittags"],
    mustSeeEn: ["Seine walk at sunset", "Le Marais and its smaller boutiques", "Montmartre early instead of midday"],
    stayAreasDe: ["Saint-Germain für klassische Paris-Stimmung", "Marais für kurze Wege", "Canal Saint-Martin für etwas entspanntere Energie"],
    stayAreasEn: ["Saint-Germain for classic Paris atmosphere", "Le Marais for walkability", "Canal Saint-Martin for a slightly calmer vibe"],
    timingDe: "Preisbewegungen sind oft stark rund um Fashion Week, Messen, Brückentage und lange Wochenenden. Gerade dann lohnt sich Monitoring bis kurz vor Anreise.",
    timingEn: "Price movement is often strong around fashion weeks, fairs, bridge holidays and long weekends. Those are exactly the moments when tracking pays off.",
  },
  barcelona: {
    highlightsDe: ["El Born", "Eixample", "Barceloneta"],
    highlightsEn: ["El Born", "Eixample", "Barceloneta"],
    stayTipDe: "Eixample ist oft ein guter Mix aus Lage, Restaurants und Ruhe. Direkt an den touristischsten Hotspots ist es oft lauter und teurer.",
    stayTipEn: "Eixample often gives you a great balance of location, food and calm. Right next to the busiest hotspots it is usually louder and pricier.",
    savingTipDe: "Barcelona kann rund um Wochenenden, Messen und Sommertermine stark schwanken. Flexible Raten sind hier besonders wertvoll.",
    savingTipEn: "Barcelona can swing hard around weekends, fairs and summer dates. Flexible rates are especially valuable here.",
    travelNoteDe: "Für viele ist die beste Mischung: Altstadt, Tapas, Strand und ein klar gesetzter Architektur-Tag statt alles auf einmal.",
    travelNoteEn: "For many travellers, the best mix is old town, tapas, beach time and one dedicated architecture day instead of trying to do everything at once.",
    premiumIntroDe: "Barcelona lebt von Kontrasten: Meer, Altstadt, breite Boulevards und starke Architektur. Gute Stadtseiten sollten genau das spiegeln, statt nur eine billige Hotel-Liste aneinanderzureihen.",
    premiumIntroEn: "Barcelona lives on contrast: sea, old town, wide boulevards and striking architecture. Strong city pages should reflect that instead of just stacking generic hotel blurbs.",
    mustSeeDe: ["Passeig de Gracia am frühen Morgen", "Tapas-Abend in El Born", "Sonnenuntergang am Bunkers del Carmel"],
    mustSeeEn: ["Passeig de Gracia early in the morning", "Tapas evening in El Born", "Sunset at Bunkers del Carmel"],
    stayAreasDe: ["Eixample für Balance", "El Born für Atmosphäre", "Poblenou für etwas mehr Ruhe nah am Wasser"],
    stayAreasEn: ["Eixample for balance", "El Born for atmosphere", "Poblenou for a calmer stay near the water"],
    timingDe: "Rund um Messen, Wochenenden und Hochsommer verschiebt sich die Preisstruktur stark. Wer früh bucht, sollte Barcelona fast immer weiter beobachten.",
    timingEn: "Around fairs, weekends and high summer the price structure moves hard. If you booked early, Barcelona is almost always worth monitoring.",
  },
  london: {
    highlightsDe: ["Covent Garden", "South Bank", "Notting Hill"],
    highlightsEn: ["Covent Garden", "South Bank", "Notting Hill"],
    stayTipDe: "In London lohnt es sich oft, eher nach guter Tube-Anbindung als nach absoluter Innenstadtlage zu buchen.",
    stayTipEn: "In London it often makes more sense to book around strong Tube access than chasing the most central postcode.",
    savingTipDe: "London-Hotels reagieren stark auf Konzerte, Fußball, Konferenzen und Ferienzeiten. Früh buchen und dann weiter tracken ist hier besonders sinnvoll.",
    savingTipEn: "London hotels react strongly to concerts, football, conferences and holiday periods. Booking early and then keeping track is especially useful here.",
    travelNoteDe: "South Bank, Parks, Pubs und ein gutes Viertel zum Zurückkommen machen London oft angenehmer als nur Sehenswürdigkeiten abzuhaken.",
    travelNoteEn: "South Bank walks, parks, pubs and having one good home neighborhood often make London better than just ticking off landmarks.",
    premiumIntroDe: "London ist selten die Stadt für den billigsten Zufallstreffer. Entscheidend sind Verbindung, Viertelgefühl und eventbedingte Sprünge. Genau deshalb ist London eine der besten Städte für späteres Rebooking.",
    premiumIntroEn: "London is rarely about finding the cheapest random room. Connection, neighborhood feel and event-driven spikes matter far more. That is exactly why London is one of the best cities for later rebooking.",
    mustSeeDe: ["South Bank zu Fuß", "Abend im Pub-Viertel", "Ein halber Tag nur für Parks und Museen"],
    mustSeeEn: ["South Bank on foot", "An evening in a pub neighborhood", "Half a day just for parks and museums"],
    stayAreasDe: ["Bloomsbury für Museen", "South Bank für Energie", "Paddington nur bei guter Verbindung und fairem Preis"],
    stayAreasEn: ["Bloomsbury for museums", "South Bank for energy", "Paddington only if the connection and price are right"],
    timingDe: "Bei Konzerten, Fußball, Schulferien und großen Konferenzen springt London extrem. Preisalarme sind hier oft kein Nice-to-have, sondern echter Schutz vor Überzahlung.",
    timingEn: "Concerts, football, school holidays and large conferences move London dramatically. Alerts here are often not a nice extra but real protection against overpaying.",
  },
  rom: {
    highlightsDe: ["Trastevere", "Centro Storico", "Monti"],
    highlightsEn: ["Trastevere", "Centro Storico", "Monti"],
    stayTipDe: "Wenn du Rom atmosphärisch erleben willst, sind Trastevere oder Monti oft spannender als sehr anonyme Kettenlagen außerhalb.",
    stayTipEn: "If you want the atmosphere of Rome, areas like Trastevere or Monti are often more rewarding than anonymous chain-hotel zones farther out.",
    savingTipDe: "Rom ist rund um Feiertage, Frühling und Herbst stark gefragt. Gerade bei länger im Voraus gebuchten Aufenthalten lohnt sich Monitoring.",
    savingTipEn: "Rome sees strong demand around holidays, spring and autumn. Monitoring is especially useful if you booked well in advance.",
    travelNoteDe: "Die Stadt funktioniert oft am besten mit viel Laufen, langen Abendessen und einem lockeren Plan pro Stadtteil.",
    travelNoteEn: "Rome often works best with lots of walking, long dinners and a relaxed plan focused on one neighborhood at a time.",
    premiumIntroDe: "Rom wirkt über Atmosphäre, Wege und Tageszeiten. Die schönsten Stunden sind oft die frühen und späten, und genau dann spürt man auch, welche Lage sich wirklich lohnt.",
    premiumIntroEn: "Rome works through atmosphere, walking and the rhythm of the day. The best hours are often early and late, and that is exactly when you feel whether your location was worth it.",
    mustSeeDe: ["Trastevere nach Sonnenuntergang", "Morgens rund ums Forum", "Ein ruhiger Aperitivo statt noch ein Museum"],
    mustSeeEn: ["Trastevere after sunset", "Morning around the Forum", "A quiet aperitivo instead of one more museum"],
    stayAreasDe: ["Monti für Stil und Nähe", "Centro Storico für klassische Wege", "Prati für etwas mehr Ruhe"],
    stayAreasEn: ["Monti for style and proximity", "Centro Storico for classic walkability", "Prati for a calmer feel"],
    timingDe: "Frühling, Herbst und Feiertage ziehen Preise in Rom schnell an. Gerade bei früher Buchung lohnt sich tägliches Nachverfolgen bis nah an die Anreise.",
    timingEn: "Spring, autumn and holidays push Rome up fast. If you booked early, daily tracking often pays right up until close to arrival.",
  },
  wien: {
    highlightsDe: ["Innere Stadt", "MuseumsQuartier", "Neubau"],
    highlightsEn: ["Innere Stadt", "MuseumsQuartier", "Neubau"],
    stayTipDe: "Wenn du Kultur, Cafes und gute Wege kombinieren willst, sind Neubau oder die Gegend um das MuseumsQuartier oft stark.",
    stayTipEn: "If you want culture, cafes and easy walking distances, Neubau and the area around the MuseumsQuartier are often strong choices.",
    savingTipDe: "Wien wirkt oft stabil, aber Messen, Adventszeit und Konzerttermine bewegen die Preise spürbar.",
    savingTipEn: "Vienna can look stable at first glance, but fairs, Christmas season and concert dates can move prices meaningfully.",
    travelNoteDe: "Schloss, Kaffeehaus, Abendkonzert und ein guter Spaziergang durch die Innenbezirke machen Wien oft besonders rund.",
    travelNoteEn: "Palaces, coffee houses, an evening concert and a good walk through the inner districts often make Vienna especially memorable.",
  },
  prag: {
    highlightsDe: ["Altstadt", "Mala Strana", "Karlsbrucke am fruhen Morgen"],
    highlightsEn: ["Old Town", "Mala Strana", "Charles Bridge early in the morning"],
    stayTipDe: "Prag ist kompakt. Du kannst oft etwas ruhiger wohnen und bist trotzdem schnell überall.",
    stayTipEn: "Prague is compact. You can often stay somewhere quieter and still get around quickly.",
    savingTipDe: "Wochenenden und Feiertage treiben die Preise schnell. Unter der Woche gibt es oft das bessere Preis-Leistungs-Verhältnis.",
    savingTipEn: "Weekends and holidays can push prices up quickly. Midweek stays often offer the better value.",
    travelNoteDe: "Frühe Spaziergänge und Abende abseits der vollsten Gassen lohnen sich oft mehr als nur die klassischen Hauptzeiten.",
    travelNoteEn: "Early walks and evenings away from the busiest lanes are often more rewarding than only following peak-hour routes.",
  },
  lissabon: {
    highlightsDe: ["Alfama", "Bairro Alto", "Belem"],
    highlightsEn: ["Alfama", "Bairro Alto", "Belem"],
    stayTipDe: "Lissabon ist hügelig. Eine schöne Lage ist gut, aber gute Erreichbarkeit spart dir jeden Tag Energie.",
    stayTipEn: "Lisbon is hilly. A pretty location is nice, but good transport access saves you energy every day.",
    savingTipDe: "Sommer, Feiertage und lange Wochenenden machen Lissabon schnell deutlich teurer. Preisalarme lohnen sich hier oft.",
    savingTipEn: "Summer, holidays and long weekends can make Lisbon noticeably pricier. Price alerts often pay off here.",
    travelNoteDe: "Aussichtspunkte, Tram-Strecken, Pastel de Nata und ein Ausflug nach Belem reichen oft schon für einen richtig guten ersten Aufenthalt.",
    travelNoteEn: "Viewpoints, tram routes, pastel de nata and a trip to Belem are often enough to make a first stay in Lisbon feel great.",
  },
  dubai: {
    highlightsDe: ["Downtown", "Dubai Marina", "Al Fahidi"],
    highlightsEn: ["Downtown", "Dubai Marina", "Al Fahidi"],
    stayTipDe: "Dubai ist weitläufig. Lageentscheidungen wirken sich hier stärker auf Taxis, Zeit und Tagesplanung aus als in vielen europäischen Städten.",
    stayTipEn: "Dubai is spread out. Location choices affect taxis, time and daily plans much more here than in many European cities.",
    savingTipDe: "Dubai-Hotelpreise reagieren stark auf Events, Ferien und Saisonwechsel. Flexible Buchungen sind hier besonders wertvoll.",
    savingTipEn: "Dubai hotel prices react strongly to events, holidays and seasonal shifts. Flexible bookings are especially valuable here.",
    travelNoteDe: "Eine gute Mischung aus moderner Skyline, Altstadt-Kontrast und Strandtag funktioniert für viele besser als nur Mall und Aussichtsturm.",
    travelNoteEn: "For many travellers, a mix of skyline, old-quarter contrast and one beach day works better than focusing only on malls and viewpoints.",
  },
  "new-york": {
    highlightsDe: ["West Village", "Central Park", "Brooklyn Heights"],
    highlightsEn: ["West Village", "Central Park", "Brooklyn Heights"],
    stayTipDe: "New York ist oft weniger eine Frage von Sternen als von Lage. Gute U-Bahn-Anbindung schlägt hier viel.",
    stayTipEn: "In New York it is often less about stars and more about location. Strong subway access matters a lot.",
    savingTipDe: "New York reagiert massiv auf Messen, Feiertage, lange Wochenenden und Großevents. Früh buchen und später weiter tracken ist hier stark.",
    savingTipEn: "New York reacts massively to fairs, holidays, long weekends and major events. Booking early and then keeping track is powerful here.",
    travelNoteDe: "Weniger Programm, mehr Viertelgefühl: ein Morgen im Park, ein Viertel am Abend und genug Zeit zwischen den Stops machen New York meist besser.",
    travelNoteEn: "Less overplanning and more neighborhood feeling usually makes New York better: a park morning, one area in the evening and enough time between stops.",
  },
  budapest: {
    highlightsDe: ["Budaer Burg", "Thermalbader", "Judesches Viertel"],
    highlightsEn: ["Buda Castle", "Thermal Baths", "Jewish Quarter"],
    stayTipDe: "Zwischen Donauseiten und Thermen ist Budapest kompakt genug für viele Wege, aber die genaue Lage beeinflusst deinen Rhythmus deutlich.",
    stayTipEn: "Between both sides of the Danube and the thermal baths, Budapest is compact enough for many walks, but exact location still shapes your pace a lot.",
    savingTipDe: "Beliebte Wochenenden und saisonale Spitzen können Preise schnell bewegen. Gerade bei verlängerten Wochenenden lohnt sich Tracking.",
    savingTipEn: "Popular weekends and seasonal peaks can move prices quickly. Tracking is especially useful for long weekend stays.",
    travelNoteDe: "Thermalbad, Donau-Abend, gutes Cafe und ein Tag zwischen Buda und Pest ergeben oft den besten Mix.",
    travelNoteEn: "A thermal bath, a Danube evening, a good cafe and one day split between Buda and Pest often create the best mix.",
  },
  bali: {
    highlightsDe: ["Ubud", "Canggu", "Uluwatu"],
    highlightsEn: ["Ubud", "Canggu", "Uluwatu"],
    stayTipDe: "Bali ist kein klassischer Stadttrip. Überlege zuerst, welche Inselstimmung du willst, statt nur nach dem billigsten Hotel zu schauen.",
    stayTipEn: "Bali is not a classic city trip. Start by deciding what kind of island atmosphere you want instead of looking only at the cheapest hotel.",
    savingTipDe: "Auf Bali lohnt sich Preisüberwachung vor allem bei Resorts und längeren Aufenthalten, bei denen kleine tägliche Unterschiede schnell groß werden.",
    savingTipEn: "On Bali, price tracking is especially useful for resorts and longer stays where small daily changes add up quickly.",
    travelNoteDe: "Ein Mix aus Ruhe, Strand und bewusst gewählter Gegend ist oft wichtiger als möglichst viele Ortswechsel.",
    travelNoteEn: "A mix of calm, beach time and a deliberately chosen area often matters more than trying to move around too much.",
  },
  mallorca: {
    highlightsDe: ["Palma", "Serra de Tramuntana", "Nordkuste"],
    highlightsEn: ["Palma", "Serra de Tramuntana", "North Coast"],
    stayTipDe: "Mallorca ist vielseitig. Palma ist gut für einen Mix aus Stadt und Meer, der Norden und Westen eher für Ruhe und Landschaft.",
    stayTipEn: "Mallorca is versatile. Palma works well for a city-and-sea mix, while the north and west feel better for scenery and calm.",
    savingTipDe: "Ferienzeiten und Wochenenden bewegen Mallorca-Hotelpreise stark. Frühe Buchungen mit Flexibilität lohnen sich hier besonders.",
    savingTipEn: "Holiday periods and weekends move Mallorca hotel prices strongly. Early bookings with flexibility are especially valuable here.",
    travelNoteDe: "Strand, Altstadt, Markt und ein Tagesausflug in die Berge machen viele Mallorca-Trips deutlich runder.",
    travelNoteEn: "Beach time, old town wandering, a market and one mountain day trip make many Mallorca stays feel much richer.",
  },
  teneriffa: {
    highlightsDe: ["Teide-Nationalpark", "La Laguna", "Costa Adeje"],
    highlightsEn: ["Teide National Park", "La Laguna", "Costa Adeje"],
    stayTipDe: "Der Norden und Süden der Insel fühlen sich sehr unterschiedlich an. Überlege zuerst, ob du mehr Natur oder mehr Resort-Komfort willst.",
    stayTipEn: "The north and south of the island feel very different. Decide first whether you want more nature or more resort comfort.",
    savingTipDe: "Bei längeren Aufenthalten oder Familienhotels summieren sich Preisunterschiede auf Teneriffa schnell.",
    savingTipEn: "For longer stays or family hotels, price differences on Tenerife add up quickly.",
    travelNoteDe: "Ein Mix aus Küste, Vulkanlandschaft und einem ruhigen Tag abseits der Resorts macht die Insel meist am besten.",
    travelNoteEn: "A mix of coast, volcanic scenery and one quiet day away from the resorts often shows the island at its best.",
  },
  zuerich: {
    highlightsDe: ["Altstadt", "Seepromenade", "Zuerich West"],
    highlightsEn: ["Old Town", "Lake Promenade", "Zurich West"],
    stayTipDe: "Zürich ist kompakt, aber teuer. Gute Lage spart hier oft mehr Zeit und Verkehrskosten als man denkt.",
    stayTipEn: "Zurich is compact but expensive. A good location often saves more time and transport cost than people expect.",
    savingTipDe: "Schon kleine Preisunterschiede können in Zürich relevant sein. Monitoring lohnt sich hier oft schon bei kurzen Aufenthalten.",
    savingTipEn: "Even small price differences can matter in Zurich. Monitoring often pays off even for short stays.",
    travelNoteDe: "See, Altstadt und ein halber Tag in Zürich West reichen vielen schon für einen sehr runden ersten Eindruck.",
    travelNoteEn: "The lake, old town and half a day in Zurich West are often enough for a very rounded first impression.",
  },
  venedig: {
    highlightsDe: ["Cannaregio", "Dorsoduro", "Lagunenblicke am fruhen Morgen"],
    highlightsEn: ["Cannaregio", "Dorsoduro", "Lagoon views early in the morning"],
    stayTipDe: "In Venedig ist die Mikro-Lage fast alles. Schon wenige Gassen Abstand von den Hauptströmen machen viel aus.",
    stayTipEn: "In Venice, micro-location is almost everything. Being just a few lanes away from the main flows changes the experience a lot.",
    savingTipDe: "Venedig kann rund um Feiertage und Wochenenden stark schwanken. Wenn du früh buchst, lohnt sich Nachverfolgung besonders.",
    savingTipEn: "Venice can swing a lot around holidays and weekends. If you book early, follow-up tracking is especially worthwhile.",
    travelNoteDe: "Venedig ist am schönsten in den Randstunden. Frühe Morgen und späte Abende verändern die ganze Reisequalität.",
    travelNoteEn: "Venice is often at its best on the edges of the day. Early mornings and late evenings can completely change the experience.",
  },
  florenz: {
    highlightsDe: ["Duomo", "Oltrarno", "Piazzale Michelangelo"],
    highlightsEn: ["Duomo", "Oltrarno", "Piazzale Michelangelo"],
    stayTipDe: "Florenz lebt von kurzen Wegen. Eine gute zentrale Lage macht hier oft mehr aus als ein großer Hotelstandard.",
    stayTipEn: "Florence is all about short distances. A good central location often matters more than a very high hotel category.",
    savingTipDe: "Gerade in Frühling und Herbst können Preise in Florenz spürbar schwanken. Preisalarme machen hier Sinn.",
    savingTipEn: "Especially in spring and autumn, Florence prices can move noticeably. Alerts make sense here.",
    travelNoteDe: "Kunst, Aussicht, gutes Essen und genug Zeit zu Fuß sind meist die richtige Kombination für Florenz.",
    travelNoteEn: "Art, viewpoints, good food and enough time on foot are usually the right combination for Florence.",
  },
  madrid: {
    highlightsDe: ["Retiro", "Malasana", "La Latina"],
    highlightsEn: ["Retiro", "Malasana", "La Latina"],
    stayTipDe: "Madrid funktioniert oft am besten mit einem Viertel, in das man abends gerne zurückkommt, statt nur maximal zentral zu wohnen.",
    stayTipEn: "Madrid often works best when you choose a neighborhood you enjoy returning to in the evening rather than just chasing the most central pin.",
    savingTipDe: "Wochenenden, Spiele und Eventtermine treiben die Preise. Früh buchen und später prüfen lohnt sich hier oft.",
    savingTipEn: "Weekends, matches and event dates push prices up. Booking early and checking later often pays off here.",
    travelNoteDe: "Museen, Abendkultur und ein spätes Essen gehören in Madrid stark zum Rhythmus der Reise.",
    travelNoteEn: "Museums, evening culture and late dinners are a big part of the rhythm of a Madrid trip.",
  },
  athen: {
    highlightsDe: ["Plaka", "Koukaki", "Akropolis-Blickpunkte"],
    highlightsEn: ["Plaka", "Koukaki", "Acropolis viewpoints"],
    stayTipDe: "Athen ist viel angenehmer, wenn du auf Hitze, Wege und Abendatmosphäre achtest und nicht nur auf den billigsten Punkt auf der Karte.",
    stayTipEn: "Athens feels much better when you think about heat, walking distances and evening atmosphere instead of only the cheapest pin on the map.",
    savingTipDe: "Preise bewegen sich hier stark mit Saison und langen Wochenenden. Wer flexibel bleibt, kann oft später noch gewinnen.",
    savingTipEn: "Prices move strongly here with seasonality and long weekends. If you stay flexible, you can often still win later.",
    travelNoteDe: "Morgens früh zu den Aussichtspunkten, mittags ruhiger und abends in den Vierteln unterwegs sein funktioniert in Athen besonders gut.",
    travelNoteEn: "Athens works especially well if you do viewpoints early, take it easier at midday and spend evenings in lively neighborhoods.",
  },
  istanbul: {
    highlightsDe: ["Sultanahmet", "Beyoglu", "Bosporus"],
    highlightsEn: ["Sultanahmet", "Beyoglu", "Bosphorus"],
    stayTipDe: "In Istanbul ist die Wahl zwischen historischer Altstadt und lebendigem modernem Viertel wichtiger als nur die Hotelkategorie.",
    stayTipEn: "In Istanbul, choosing between the historical old city and the livelier modern side matters more than just hotel category.",
    savingTipDe: "Istanbul hat oft spürbare Ratenschwankungen. Gerade bei früher Buchung kann tägliches Monitoring interessant sein.",
    savingTipEn: "Istanbul often shows meaningful rate swings. Daily tracking can be especially interesting if you booked early.",
    travelNoteDe: "Bosporus, Moscheen, Märkte und Fähren sorgen meist für den besten Mix aus Atmosphäre und Orientierung.",
    travelNoteEn: "The Bosphorus, mosques, markets and ferries usually create the best mix of atmosphere and orientation.",
  },
};

export function getCityGuide(slug: string): CityGuide | null {
  return cityGuides[slug] ?? null;
}
